### ISSUE TITLE
有没有支持英文的打算？

### ISSUE THREAD

**Issue by shen2009fei** [huakunyang/SummerTTS#1]

**Comment by huakunyang** [comment]
会考虑支持，支持英文代码需要少许修改，模型需要重新训练，需要一些时间了。

**Comment by shen2009fei** [comment]
我测试了一下 inference 要6.3秒。
这种情况 对于实时性要求高的应用就受不了了，如果能优化到200ms内就完美了。


(base) ➜  build git:(main) ✗ ./tts_test ../test.txt ../models/single_speaker_small.bin out.wav
model size:63081332
Model loadModel takes 0.065956s.
Available speakers in the model are 1
Model inference takes 6.313679s.
Model convert takes 0.000025s.
Model write takes 0.005164s.

**Comment by huakunyang** [comment]
现在速度是比较慢，这段测试的语音大概是6秒，用small 模型 合成也需要6秒，你可以先试一试 tiny 模型，速度要快一倍左右，三秒能完成，合成音质在听感上没有太大的区别。

其中耗时最大的模块是hifigan 声码器，我正在考虑用其他 声码器 代替 hifigan，如果可行，速度能提升很多倍，但是否能达到你说的200ms，还是非常有挑战的，毕竟eigein库的性能不算太高。你可以等我这个改动完成后再试一试。

**Comment by shen2009fei** [comment]
> 现在速度是比较慢，这段测试的语音大概是6秒，用small 模型 合成也需要6秒，你可以先试一试 tiny 模型，速度要快一倍左右，三秒能完成，合成音质在听感上没有太大的区别。
> 
> 其中耗时最大的模块是hifigan 声码器，我正在考虑用其他 声码器 代替 hifigan，如果可行，速度能提升很多倍，但是否能达到你说的200ms，还是非常有挑战的，毕竟eigein库的性能不算太高。你可以等我这个改动完成后再试一试。

我用tiny 测试下来 时间只要3秒，时间少了一半，如你所说，音质没多少区别。我不是从事这个领域的，我的想法就是如果能将它控制在一个很短的时间内，部署到安卓和iOS上，有英文多人语音对话模型，就完美了。

大佬能否推荐推荐 这个领域的入门资料？

**Comment by huakunyang** [comment]
> > 现在速度是比较慢，这段测试的语音大概是6秒，用small 模型 合成也需要6秒，你可以先试一试 tiny 模型，速度要快一倍左右，三秒能完成，合成音质在听感上没有太大的区别。
> > 其中耗时最大的模块是hifigan 声码器，我正在考虑用其他 声码器 代替 hifigan，如果可行，速度能提升很多倍，但是否能达到你说的200ms，还是非常有挑战的，毕竟eigein库的性能不算太高。你可以等我这个改动完成后再试一试。
> 
> 我用tiny 测试下来 时间只要3秒，时间少了一半，如你所说，音质没多少区别。我不是从事这个领域的，我的想法就是如果能将它控制在一个很短的时间内，部署到安卓和iOS上，有英文多人语音对话模型，就完美了。
> 
> 大佬能否推荐推荐 这个领域的入门资料？

呃，多人对话需要NLP 和 NLG ，这方面我也不太懂。。。

**Comment by huakunyang** [comment]
> > 现在速度是比较慢，这段测试的语音大概是6秒，用small 模型 合成也需要6秒，你可以先试一试 tiny 模型，速度要快一倍左右，三秒能完成，合成音质在听感上没有太大的区别。
> > 其中耗时最大的模块是hifigan 声码器，我正在考虑用其他 声码器 代替 hifigan，如果可行，速度能提升很多倍，但是否能达到你说的200ms，还是非常有挑战的，毕竟eigein库的性能不算太高。你可以等我这个改动完成后再试一试。
> 
> 我用tiny 测试下来 时间只要3秒，时间少了一半，如你所说，音质没多少区别。我不是从事这个领域的，我的想法就是如果能将它控制在一个很短的时间内，部署到安卓和iOS上，有英文多人语音对话模型，就完美了。
> 
> 大佬能否推荐推荐 这个领域的入门资料？

今天更新的代码和模型中，速度已经大幅度的提升了，欢迎试试看

**Comment by andyuan1000** [comment]
现在这个版本英文还是不支持的

**Comment by huakunyang** [comment]
> 现在这个版本英文还是不支持的

下周可能会有一个版本支持全英文的语音合成，但中英文混合的合成，暂时还没那么快能实现。

**Comment by huakunyang** [comment]
今天的更新支持了纯英文的语音合成，中英文混合的语音合成暂时还不支持，但已经被 #issue6 记录，所以这个我就关了。
