### ISSUE TITLE
请问模型初始后，每次调用合成是否会提高速度？

### ISSUE THREAD

**Issue by xiongfeigood** [huakunyang/SummerTTS#10]
请问如果第一次加载了模型，再次合成的时候，是否能提高速度？
如果是的话建议增加一个接口：初始化模型，然后之后就只需要调用合成接口，直接合成语音。
由于我不是很专业，不知道我理解的是否正确，谢谢。

**Comment by huakunyang** [comment]
这样的接口是有的，就是 infer 接口，Readme的里面也有说明，test/main.cpp 只是个使用 SynthesizerTrn 的Demo程序，在下面的这一行代码，初始化和加载了模型：
SynthesizerTrn * synthesizer = new SynthesizerTrn(dataW, modelSize);

在这一行调用对象 的 infer 执行合成：
 int16_t * wavData = synthesizer->infer(line,0, 1.0,retLen);

你们完全可以在你们的代码中，初始化一次后，多次调用infer 执行合成，这样就不必每次加载模型，会快一些，也可能会节省一些内存。
