### ISSUE TITLE
是否考虑从工具向转SDK向

### ISSUE THREAD

**Issue by endink** [huakunyang/SummerTTS#16]
- 可单独编译 C++推理库（静态、动态，跨平台或者至少跨 Desktop 操作系统）
- 可泛用的模型转换脚本

这些是刚需啊~   

PS： 被 paddle speech 折磨得苦不堪言，它得 CPU 推理太慢了，转 ONNX 有茫茫多的 BUG

**Comment by huakunyang** [comment]
你说的这些问题，作为AI 工具链 其实比较难，因为要对接上下游，而AI模型日新月异，上下游都变化得很快，所以AI 工具链不容易作得让所有人满意。
