### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by dididiskq** [huakunyang/SummerTTS#17]
./tts_test ../test.txt ../models/single_speaker_fast.bin out.wav

**Comment by huakunyang** [comment]
能提供更多信息么？ 比如平台什么的 ？ 我运行起来没有crash。 能检查一下平台内存是否够，以及对应位置程序是否有写文件的权限，以及模型下载是否完 ? 检查一下模型的md5 是不是下面一样的？

ede610a051a7a15abcdd94ff2ae167a3  ../models/single_speaker_fast.bin

**Comment by dididiskq** [comment]
已解决，应该是权限问题，效果不错，感谢
