### ISSUE TITLE
有没有兴趣支持一下多音字

### ISSUE THREAD

**Issue by wbjnpu** [huakunyang/SummerTTS#2]
用g2p模型推理的方法

**Comment by huakunyang** [comment]
> 用g2p模型推理的方法

嗯，TN 的加强和多音字的支持会后续作吧，不知道中文的g2p效果如何。

**Comment by wbjnpu** [comment]
> > 用g2p模型推理的方法
> 
> 嗯，TN 的加强和多音字的支持会后续作吧，不知道中文的g2p效果如何。

论文上看起来指标还行

**Comment by wbjnpu** [comment]
> > > > 用g2p模型推理的方法
> > > 
> > > 
> > > 嗯，TN 的加强和多音字的支持会后续作吧，不知道中文的g2p效果如何。
> > 
> > 论文上看起来指标还行
> 
> 能给个论文和代码的链接吗？

搜一下g2pw，开源了onnx模型和推理

**Comment by huakunyang** [comment]
多音字的发音 在今天(6 月 2 日）的版本已经较大幅度的改善了，虽然没有使用g2p :-P
欢迎试用尝试多音字。

**Comment by huakunyang** [comment]
音字的发音 在今天(6 月 2 日）的版本已经较大幅度的改善了，这个我就关了

**Comment by wbjnpu** [comment]
> 多音字的发音 在今天(6 月 2 日）的版本已经较大幅度的改善了，需要使用今天的代码和网盘上更新的模型，虽然没有使用g2p :-P
> 欢迎试用尝试多音字。

是用的规则么

**Comment by huakunyang** [comment]
> > 多音字的发音 在今天(6 月 2 日）的版本已经较大幅度的改善了，需要使用今天的代码和网盘上更新的模型，虽然没有使用g2p :-P
> > 欢迎试用尝试多音字。
> 
> 是用的规则么

大致过程如下：
1. 判断该字是否是多音字
2. 如果是多音字，对原句分词，找出包含该多音字的词语
3. 查表找出该词的发音，这是一个很大的表，包含常见的多音字的词语的发音
