### ISSUE TITLE
想请教一下如何控制音量、音调呢

### ISSUE THREAD

**Issue by 5m1le71ger** [huakunyang/SummerTTS#26]
我可以控制语速，但是似乎不能控制音量、音调(pitch)

另外我如果要生成采样率为8000hz的文件，该如何做呢，电话里的语音用的都是8000hz的

**Comment by huakunyang** [comment]
直接在生成的PCM 上改变音量，音调和采样率吧，很容易作的，网上有很多开源资源，你找找看。
