### ISSUE TITLE
multi模型设定说话人

### ISSUE THREAD

**Issue by Isshang** [huakunyang/SummerTTS#31]
简单好用，先点一个赞。
使用multi合成的时候默认生成了十个不同说话人的十条语音，麻烦问一下可以指定aishell3的某一个说话人吗？参数是什么呢，没找到呢

**Comment by huakunyang** [comment]
具体合成的接口定义在 include/SynthesizerTrn.h， 如下,第二个参数指定说话人：

int16_t * infer(const string & line, int32_t sid, float lengthScale, int32_t & dataLen)

该接口的：
第一个参数是待合成的语音的字符串。
第二个参数指定说话人的id 用于合成语音，该参数对多说话人模型有效，对单说话人模型，固定为0。说话人的个数可由接口 int32_t getSpeakerNum() 返回，有效id 为 0 到 该接口返回的说话人数量减1。
第三个参数 lengthScale 表示合成语音的语速，其值越大表示语速越慢。
