### ISSUE TITLE
GPU 加速

### ISSUE THREAD

**Issue by Isshang** [huakunyang/SummerTTS#34]
麻烦问一下，目前的c++是cpu计算的吗？我了解到Eigen 不能加入GPU，咱们项目可以使用GPU进行加速吗？

**Comment by huakunyang** [comment]
目前的编译选项是使用的cpu，eigen的底层可以使cuda，但是我没有试过，可能会有一些问题。基于gpu的TTS已经有很多方案了，你可以找找看

**Comment by Isshang** [comment]
好的，谢谢啦
