### ISSUE TITLE
请问是否可以增加一个安卓中使用的例子？

### ISSUE THREAD

**Issue by watersoft123** [huakunyang/SummerTTS#51]
你好，是否可以提供个安卓的例子，不知道如何写接口，谢谢

**Comment by huakunyang** [comment]
请参考这个项目：https://github.com/SchweitzerGAO/SummerTTS-Android

**Comment by watersoft123** [comment]
> 请参考这个项目：https://github.com/SchweitzerGAO/SummerTTS-Android

谢谢，模型能裁剪的小一点就更好了

**Comment by watersoft123** [comment]
> 请参考这个项目：https://github.com/SchweitzerGAO/SummerTTS-Android

谢谢，模型能裁剪的小一点就更好了
