### ISSUE TITLE
不支持换行及空格

### ISSUE THREAD

**Issue by andyuan1000** [huakunyang/SummerTTS#9]
只支持一段话。能否支持整篇文章的文字转语音，包括文章空格，空行 换行等特殊条件

**Comment by huakunyang** [comment]
> 只支持一段话。能否支持整篇文章的文字转语音，包括文章空格，空行 换行等特殊条件

修改了 test/main.cpp , 现在支持换行和整篇文本的合成。请使用今天刚才更新的版本。

**Comment by huakunyang** [comment]
今天的更新支持换行和整篇文本的合成， 这个我就关了。
